services:
  - type: web
    name: capstone-subscriptions
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn subscription_manager.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: capstone-db
          property: connectionString
databases:
  - name: capstone-db
