services:
  - type: web
    name: subscriptions-manager
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn subscription_manager.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: subscriptions-db
          property: connectionString
      - key: DEBUG
        value: True
      - key: DJANGO_SECRET_KEY
        generateValue: true
databases:
  - name: subscriptions-db
    plan: free
